
# Set the source directory for Jekyll (where your Jekyll site's source files are located)
source: src

# Set the destination directory for Jekyll (where Jekyll will output the built site)
destination: public


# Site settings
title: Your Jekyll Site
description: A brief description of your site

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal # Change this to the desired theme or remove for no theme


# Sass/SCSS configuration
sass:
  source: ../src
  sass_dir: assets/css/style.scss
  style: :compressed


# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - .github
  - _site

# Plugins
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# GitHub Metadata for GitHub Pages
github:
  show_downloads: false

# Permalinks
permalink: /:title/

# Any other custom configurations specific to your project

# Exclude files or directories that should not be processed by Jekyll
exclude:
  - node_modules

